### ISSUE TITLE
Broken website feeds

### ISSUE THREAD

**Issue by garrett** [gluster/planet-gluster#20]
When building, I get the following site feed errors and warnings:

``` yaml
ERR:  Server sent 'text/html'; problem parsing 'http://devincharge.com/gluster/feed/'
ERR:  HTTP 400: Problem downloading 'https://lalatendumohanty.wordpress.com/category/glusterfs/feed/'
ERR:  Problem getting HTTP HEAD of 'https://blog.coildomain.com/category/storage/feed/'; site down or cert issue?
ERR:  HTTP unknown error: Problem downloading 'https://blog.coildomain.com/category/storage/feed/'
WARN: Switch http://jonarcher.info/tag/gluster/feed/ to HTTPS in data/feeds.yml
ERR:  HTTP 400: Problem downloading 'https://mjanja.co.ke/tag/glusterfs/feed/'
ERR:  HTTP 400: Problem downloading 'https://neependra.net/?tag=glusterfs&amp;feed=atom?tag=glusterfs&amp;fee.'
ERR:  Problem getting HTTP HEAD of 'https://www.blogger.com/feeds/7976893974966932012/posts/default'; site down or cert issue?
ERR:  HTTP unknown error: Problem downloading 'https://www.blogger.com/feeds/7976893974966932012/posts/default'
ERR:  Problem getting HTTP HEAD of 'https://www.severalnines.com/taxonomy/term/122/0/feed'; site down or cert issue?
ERR:  HTTP unknown error: Problem downloading 'https://www.severalnines.com/taxonomy/term/122/0/feed'
WARN: Switch http://www.severalnines.com/taxonomy/term/122/0/feed to HTTPS in data/feeds.yml
ERR:  Problem getting HTTP HEAD of 'https://kshlm.in/tag/gluster/rss'; site down or cert issue?
ERR:  HTTP unknown error: Problem downloading 'https://kshlm.in/tag/gluster/rss'
```

This basically means that the sites are down, the URLs are incorrect, or have some issues with rendering the RSS/Atom.
